### PR TITLE
build: Setup GitHub Actions for builds on PRs and releases

### PR DESCRIPTION
**Pull request by atallahhezbor**

### CODE REVIEW

**Comment by Shinkson47** [comment]
For the sake of having a cleaner history, could we cherry pick the important commits?

**Comment by atallahhezbor** [comment]
@Shinkson47 I'm an advocate of squashing and merging, which will reduce it to a single commit

**Comment by atallahhezbor** [comment]
Although this does also add wwise linux integrations... so perhaps it would be cleaner to pull that out

**Comment by galdchen** [comment]
So are we squishing or cherry picking or what?

**Comment by atallahhezbor** [comment]
@galdchen I'm gonna go ahead and squash. since we had to add linux integrations for build purposes, all the commits here are related enough to be bundled up. Unfortunately this means that your tender pleas of `LORD PLEASE GOD !!!` and `I dont know dude...` will be lost to history. Here's hoping there's no hidden magic in those words

**Pull request merged**
