### PR TITLE
Merge sprint 1

### PR DESCRIPTION
**Pull request by solerfranco**
Due to some misunderstandings, multiple branches are being reviewed at once. The merge-sprint-1 branch has all the features belonging to sprint 1, which have not been individually reviewed.

This being: The Entity-Movement System, Camera System, Playground-Map, and Menu Screen.

Corresponding files to each system/feature
# Entity-Movement:

- Entity (Prefab)
- EntityMovmentScript (Script)

# Camera System:

- CameraBehaviour (Script)
- DemoCameraController (Script) [This is just to test features until that behaviour is somewhere else]

# Playground-Map:

- TestingGround (Scene)
- Tiles (Folder in sprites) [it has all the necessary files for the tile system like ProtoPalette, Placeholders, and TileRules.]

# Menu Screen:

- MainMenu (Scene)
- Menu (Script)
- ObjectHover (Script)
- Menu (Folder in Audio)
- Placeholder_Background (Sprite)
- Menu (Folder in Animations)
- Torte (Font)

# Miscellaneous things that don't belong on this sprint:

Character animations
AnimationController (Script)
Character sprites

### CODE REVIEW

**Review by Shinkson47 — CHANGES_REQUESTED** [review]
It's all coming together, looks great!

A few notes of consideration for behind the scenes:


- [x] EntityMovementScript:73 Should we be keeping a youtube URL in our source?
- [x] EntityMovementScript:111-112 Commented code (I believe it's waiting on an input scene design)

- [x] CameraBehaviour: No docstrings
- [x] CameraBehaviour:55 Has a getter name, but is a field. Could this calculation just be moved to `cameraSize` or mutated into a function?
- [x] CameraBehaviour:70 This is duplicated code, we have a function for this (103 : ReturnFocusToPrimary)
- [x] CameraBehaviour:75 Tilemap assignment in editor is required, but there's no null check - although unity handles this well
- [x] CameraBehavior:84 We no longer need to be printing co-ordinates on every update.

ObjectHover: Great use of inheritance!
- [x] ObjectHover: `{..}` are redundant for `if` bodies that only contain one statement
- [x] ObjectHover:15 `hover` seems redundant, could literal values be used on `anim.SetBool` instead?

- [x] Menu: No docstrings
- [x] Menu:16-23 Redundant `{}` on if's
- [x] Menu:28, 34 These can be lambda
- [x] Menu:56 This log seems un-necassary

MenuScene: Is labelling exit as "*commit exit*" suitable for mainstream? Is it possibly a trigger?

- [x] AnimationController, DemoCameraController: These are testing scripts, do we still need to include them?
- [x] SampleScene: This testing scene is not used, do we still need it?
- [x] Some asset folders can now have thier placeholder touches removed

**Review by Shinkson47 — APPROVED** [review]
She do be lookin' mighty fine

I won't merge to await Gal and Atallah's reviews

**Review by galdchen — APPROVED** [review]
Some small issues with collision, but the code looks good.

**Review by atallahhezbor — APPROVED** [review]
LGTM as far as I can tell!

**Pull request merged**
